name: Tribezilla
favicon: null
layout_spectrum: 0.8737838445231318
typography_spectrum: 0.6021161458920687
title: 'Tribezilla! The event horizon of technological singularity.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-30892242-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6921e'
    - '#6d6e70'
    - '#000000'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0.6328529056627303
  lightness: 0.5
  saturation: 0.8258108447771519
  rhythmicContrast: 0.9771094671450555
purpose: []
